config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index'

  resources :profiles
  resources :ordering_links
  devise_for :admins
  resources :socials
  get 'pages/index'
  get 'pages/order_online'
  get 'pages/about'
  
  scope :admins do
    root :to => 'dashboards#index', :as => :admin_root
  end
  
  root 'pages#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :admin
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:show]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end
  
  # GET /profiles/new
  def new
    #@profile = Profile.new
    @profile = current_admin.profiles.build
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    #@profile = Profile.new(profile_params)
    @profile = current_admin.profiles.build(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to dashboards_index_path, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profiles_url, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:restaurant_name, :short_intro, :address, :about, :phone_number, :email, :iphone_app, :android_app, :monday_hours, :tuesday_hours, :wednesday_hours, :thursday_hours, :friday_hours, :saturday_hours, :sunday_hours, :facebook_url, :twitter_url, :instagram_url, :ordering_url)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_footer.html.erb
<!--begin footer -->
    <div class="footer">
        <!--begin container -->
        <div class="container">
            <!--begin row -->
            <div class="row footer-top">
                <!--begin col-md-3 -->
                <div class="col-md-3 padding-bottom-50">
                	<h4>ABOUT US</h4>
                    
                        <p><%= @profile.about %></p>
                    
                </div>
                <!--end col-md-3 -->
                <!--begin col-md-3 -->
                <div class="col-md-3 padding-bottom-50">
                	<h4>LATEST RECIPES</h4>
                    <ul class="footer-list">
                        <li class="first"><a href="#" target="blank">Cheddar Cheese Cauliflower Tots</a></li>
                        <li><a href="#" target="blank">Garlic Chicken &amp; White Wine Sauce</a></li>
                        <li><a href="#" target="blank">Spinach Mozzarella Grilled Cheese</a></li>
                        <li><a href="#" target="blank">Mini Chicken Roasted Cups</a></li>
					</ul>
                </div>
                <!--end col-md-3 -->
                <!--begin col-md-3 -->
                <div class="col-md-3 padding-bottom-50">
                	<h4>FEATURED DISHES</h4>
                    <ul class="footer-gallery">
                        <li class="popup-gallery">
                            <a class="popup2" href="/assets/images/instagram1-large.jpg">
                                <%= image_tag 'instagram1.jpg' %>
                            </a>
                        </li>
                        <li class="popup-gallery">
                            <a class="popup2" href="images/instagram6-large.jpg">
                            	<%= image_tag 'instagram6.jpg' %>
                            </a>
                        </li>
                        <li class="popup-gallery">
                            <a class="popup2" href="images/instagram2-large.jpg">
                            	<%= image_tag 'instagram2.jpg' %>
                            </a>
                        </li>
                        <li class="popup-gallery">
                            <a class="popup2" href="images/instagram4-large.jpg">
                            	<%= image_tag 'instagram4.jpg' %>
                            </a>
                        </li>
                        <li class="popup-gallery">
                            <a class="popup2" href="images/instagram5-large.jpg">
                            	<%= image_tag 'instagram5.jpg' %>
                            </a>
                        </li>
                        <li class="popup-gallery">
                            <a class="popup2" href="images/instagram3-large.jpg">
                            	<%= image_tag 'instagram3.jpg' %>
                            </a>
                        </li>
					</ul>
                </div>
                <!--end col-md-3 -->
                <!--begin col-md-3 -->
                <div class="col-md-3 padding-bottom-50">
                	<h4>CONTACT DETAILS</h4>
                    
                        <p class="contact_info">
                            <ul>
                                <li>Monday: <%= @profile.monday_hours %></li>
                                <li>Tuesday: <%= @profile.tuesday_hours %></li>
                                <li>Wednesday: <%= @profile.wednesday_hours %></li>
                                <li>Thursday: <%= @profile.thursday_hours %></li>
                                <li>Friday: <%= @profile.friday_hours %></li>
                                <li>Saturday: <%= @profile.saturday_hours %></li>
                                <li>Sunday: <%= @profile.sunday_hours %></li>
                            </ul>
                        </p>
                        <p class="contact_info"><i class="fa fa-map-marker"></i> <%= @profile.address %></p>
                        <p class="contact_info"><i class="fa fa-phone"></i> <%= @profile.phone_number %></p>
                        <p class="contact_info"><i class="fa fa-envelope-square"></i> <%= @profile.email %></p>
                    
                </div>
                <!--end col-md-3 -->
            </div>
            <!--end row -->
            <!--begin row -->
            <div class="row">
                <!--begin footer-bottom -->
                <div class="footer-bottom">
                    <!--begin col-md-5 -->
                    <div class="col-md-5">
                        <!--begin copyright -->
                        <div class="copyright ">
                            <p>© 2016 Fable. Designed by <%= link_to 'The Cookie Dining', 'http://thecookiedining.com', target: "_blank" %></p>
                        </div>
                        <!--end copyright -->
                    </div>
                    <!--end col-md-5 -->
                    <!--begin col-md-2 -->
                    <div class="col-md-2 text-center">
                    	<a href="#hero-section" class="scrool top-scroll"><i class="fa fa-angle-double-up"></i></a>
                    </div>
                    <!--end col-md-2 -->
                    <!--begin col-md-5 -->
                    <div class="col-md-5">
                        <!--begin footer_social -->
                        <ul class="footer_social">
                            <li>
                                Follow Us:
                            </li>
                            
                                <% if @profile.facebook_url.present? %>
                                   <li class="social">
                                       <%= link_to "http://facebook.com/#{@profile.facebook_url}", target: "_blank", class: "first" do %>
                                           <i class="fa fa-facebook"></i>
                                       <% end %>
                                   </li>
                                <% end %>
                                <% if @profile.twitter_url.present? %>
                                   <li class="social">
                                       <%= link_to "http://twitter.com/#{@profile.twitter_url}", target: "_blank" do %>
                                           <i class="fa fa-twitter"></i>
                                       <% end %>
                                   </li>
                                <% end %>
                                <% if @profile.instagram_url.present? %>
                                   <li class="social">
                                       <%= link_to "http://instagram.com/#{@profile.instagram_url}", target: "_blank", class: "last" do %>
                                           <i class="fa fa-instagram"></i>
                                       <% end %>
                                   </li>
                                <% end %>
                            
                        </ul>
                        <!--end footer_social -->
                    </div>
                    <!--end col-md-5 -->
                </div>
                <!--end footer-bottom -->
            </div>
            <!--end row -->
        </div>
        <!--end container -->
    </div>
    <!--end footer -->

app/views/profiles/_form.html.erb
<div class="row">
  


<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="col-md-6">
  <div class="form-group">
    <%= f.label :restaurant_name %><br>
    <%= f.text_field :restaurant_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :short_intro %><br>
    <%= f.text_field :short_intro, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :about %><br>
    <%= f.text_area :about, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :ordering_url %>
    <%= f.text_field :ordering_url, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :iphone_app %><br>
    <%= f.text_field :iphone_app, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :android_app %><br>
    <%= f.text_field :android_app, class: "form-control" %>
  </div>
</div>

<div class="col-md-6">
  <div class="form-group">
    <%= f.label :monday_hours %><br>
    <%= f.text_field :monday_hours, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :tuesday_hours %><br>
    <%= f.text_field :tuesday_hours, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :wednesday_hours %><br>
    <%= f.text_field :wednesday_hours, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :thursday_hours %><br>
    <%= f.text_field :thursday_hours, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :friday_hours %><br>
    <%= f.text_field :friday_hours, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :saturday_hours %><br>
    <%= f.text_field :saturday_hours, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :sunday_hours %><br>
    <%= f.text_field :sunday_hours, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :facebook_url %><br>
    <%= f.text_field :facebook_url, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :twitter_url %><br>
    <%= f.text_field :twitter_url, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :instagram_url %><br>
    <%= f.text_field :instagram_url, class: "form-control" %>
  </div>
  
</div>
<div class="form-group">
    <%= f.submit class: "bth btn-lg btn-yellow" %>
  </div>
<% end %>

</div>

app/views/profiles/_header.html.erb
   <!--begin header -->
    <header class="header">
        <!--begin nav -->
        <nav class="navbar navbar-default navbar-fixed-top">
            <!--begin container -->
            <div class="container">
                <!--begin navbar -->
                <div class="navbar-header">
                    <button data-target="#navbar-collapse-02" data-toggle="collapse" class="navbar-toggle" type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <%= link_to root_path, class: "navbar-brand brand scroll" do %>
                        <%= image_tag 'logo.png', class: "width-100" %>
                    <% end %>
                </div>
                <div id="navbar-collapse-02" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">			      
                            
                        <li><%= link_to 'Change Location', root_path %></li>
                            <% if @profile.facebook_url.present? %>
                               <li class="social">
                                   <%= link_to "http://facebook.com/#{@profile.facebook_url}", target: "_blank", class: "first" do %>
                                       <i class="fa fa-facebook"></i>
                                   <% end %>
                               </li>
                            <% end %>
                            <% if @profile.twitter_url.present? %>
                               <li class="social">
                                   <%= link_to "http://twitter.com/#{@profile.twitter_url}", target: "_blank" do %>
                                       <i class="fa fa-twitter"></i>
                                   <% end %>
                               </li>
                            <% end %>
                            <% if @profile.instagram_url.present? %>
                               <li class="social">
                                   <%= link_to "http://instagram.com/#{@profile.instagram_url}", target: "_blank", class: "last" do %>
                                       <i class="fa fa-instagram"></i>
                                   <% end %>
                               </li>
                            <% end %>
                          
                        <li><button class="btn btn-warning btn-lg purchase" data-toggle="modal" data-target="#myModal">Order Online</button></li>
                    </ul>
                </div>
                <!--end navbar -->
            </div>
    		<!--end container -->
        </nav>
    	<!--end nav -->
    </header>
    <!--end header -->

app/views/profiles/about.html.erb
<h1> About page</h1>

app/views/profiles/edit.html.erb
<%= render 'dashboards/generic' %>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title" style="font-size: 20px;">Update Location</h3>
                </div>
                <div class="panel-body">
                    <%= render 'form' %>
                </div>
              <div class="panel-footer"><%= link_to 'Cancel', profiles_path %></div>
            </div>                       
        </div>
    </div>
</div>

app/views/profiles/index.html.erb
<%= render 'dashboards/generic' %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <p id="notice"><%= notice %></p>
      <h2>My Locations</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Restaurant name</th>
            <th>Address</th>
            <th>Phone number</th>
            <th>Email</th>
            <th colspan="2"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @profiles.each do |profile| %>
            <tr>
              <td><%= profile.restaurant_name %></td>
              <td><%= profile.address %></td>
              <td><%= profile.phone_number %></td>
              <td><%= profile.email %></td>
              <td>
                <%= link_to edit_profile_path(profile) do %>
                  <i class="fa fa-pencil-square-o"></i> Update
                <% end %>
              </td>
              <td>
                <%= link_to profile, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="fa fa-trash-o"></i> Delete Location
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <br>
      <%= link_to 'New Location', new_profile_path, class: "btn btn-lg btn-yellow" %> | <%= link_to 'Back', dashboards_index_path, class: "btn btn-lg btn-white-grey" %>
    </div>
  </div>
</div>


<%= render 'dashboards/footer' %>

app/views/profiles/new.html.erb
<%= render 'dashboards/generic' %>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title" style="font-size: 20px;">New Restaurant Location</h3>
                </div>
                <div class="panel-body">
                    <%= render 'form' %>
                </div>
              <div class="panel-footer"><%= link_to 'Cancel', profiles_path %></div>
            </div>                       
        </div>
    </div>
</div>

app/views/profiles/show.html.erb
<%= render 'profiles/header' %>
<section id="hero-section" class="home-hero-section">
        <!--begin image-overlay -->
        <div class="image-overlay"></div>
        <!--end image-overlay -->
        <!--begin container-->
        <div class="container image-section-inside">
            <!--begin row-->
            <div class="row">
                <!--begin col-md-10-->
                <div class="col-md-10 col-md-offset-1 text-center">
                    
                        <h2 class="section-title white">Welcome to <%= @profile.restaurant_name %></h2>
                        <p class="hero-text"><%= @profile.short_intro %></p>    
                    
                </div>
                <!--end col-md-10-->
            </div>
            <!--end row-->
        </div>
        <!--end container-->    
    </section>
    <!--begin section-white-->
    <section class="section-white">
        <!--begin container-->
        <div class="container"> 
            <!--begin row-->
            <div class="row">
                <!--begin col-md-6-->
                <div class="col-md-6 text-center padding-top-50 padding-bottom-50">
                    <span class="comic-text">Discover</span>
                    <h2 class="section-title">Our Story</h2>
                    
                        <p><%= @profile.about %></p>
                        <%= link_to "More About Us", pages_about_path, class: "btn btn-lg btn-yellow" %>
                    
                </div>
                <!--end col-md-6-->
                <!--begin col-md-6-->
                <div class="col-md-6">
                    <!--begin carousel1-->
                    <div id="myCarousel1" class="carousel carousel1 slide" data-interval="true">
                        <!--begin carousel-inner-->
                        <div class="carousel-inner">
                            <!--begin carousel item-->
                            <div class="item active">
                                <!--begin image-wrapper-->
                                <div class="image-wrapper">
                                    <%= image_tag 'food3.jpg', class: "width-100" %>
                                </div>
                                <!--end image-wrapper-->
                            </div>
                            <!--end carousel item-->
                            <!--begin carousel item-->
                            <div class="item">
                                <!--begin image-wrapper-->
                                <div class="image-wrapper">
                                    <%= image_tag 'food2.jpg', class: "width-100" %>
                                </div>
                                <!--end image-wrapper-->
                            </div>
                            <!--end carousel item-->
                        </div>
                        <!--end carousel-inner-->
                        <!-- begin carousel-indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#myCarousel1" data-slide-to="0" class="active"></li>
                            <li data-target="#myCarousel1" data-slide-to="1"></li>
                        </ol>
                        <!-- end carousel-indicators -->
                            
                    </div>
                    <!--end carousel1-->
                </div>
                <!--end col-md-6-->
            </div>
            <!--end row-->
        </div>
        <!--end container-->
    </section>
    <!--end section-white-->
    <!--begin image-section -->
    <section class="image-section">
        <!--begin image-overlay -->
        <div class="image-overlay"></div>
        <!--end image-overlay -->
        <!--begin container-->
        <div class="container image-section-inside">
            <!--begin row-->
            <div class="row">
                
                            <!--begin col-md-10-->
                            <div class="col-md-10 col-md-offset-1 text-center">
                    
                                <span class="comic-text">Skip the line - Order online</span>
                                <br>
                                <br>
                                <div class="row">
                                        <% if @profile.iphone_app.present? && @profile.android_app.present? %>
                                            <div class="col-md-6">
                                                <%= link_to @profile.iphone_app do %>
                                                    <%= image_tag 'app-store.png', class: "img-rounded" %>
                                                <% end %>
                                            </div>
                                            <div class="col-md-6">
                                                <%= link_to @profile.android_app do %>
                                                    <%= image_tag 'get-it-on-google-play.jpg', class: "img-rounded" %>
                                                <% end %>
                                            </div>       
                                        <% elsif @profile.iphone_app.present? && @profile.android_app.blank? %>
                                            <div class="col-md-12">
                                                <%= link_to @profile.iphone_app do %>
                                                    <%= image_tag 'app-store.png', class: "img-rounded" %>
                                                <% end %>
                                            </div>
                                        <% elsif @profile.iphone_app.blank? && @profile.android_app.present? %>
                                            <div class="col-md-12">
                                                <%= link_to @profile.android_app do %>
                                                    <%= image_tag 'get-it-on-google-play.jpg', class: "img-rounded" %>
                                                <% end %>
                                            </div>
                                        <% elsif @profile.iphone_app.blank? && @profile.android_app.blank? %>
                                           <button class="btn btn-warning btn-lg purchase" data-toggle="modal" data-target="#myModal">Order Online</button>
                                        <% end %>
                                </div>
                                <!-- end of row -->
                            </div>
                            <!-- col-md-10 col-md-offset-1 text-center end -->
                        
                    
                    
            </div>
            <!--end row-->
        </div>
        <!--end container-->
    </section>
    <!--end image-section -->
    <!--begin instagram feed -->
    <div id="instafeed">
        <!--begin iinstagram-text -->
        <div class="instagram-text">
            <a href="#" target="_blank" class="instagram-icon"><i class="fa fa-instagram"></i></a>
            <p>Follow us on Instagram!</p>
        </div>
        <!--end instagram-text -->
    </div>
    <!--end instagram feed -->
    
    
   
   

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        
      </div>
      <div class="modal-body">
           <iframe width="100%" height="1050" src="<%= @profile.ordering_url %>" frameborder="0" allowfullscreen>
            </iframe>
      </div>
    </div>
  </div>
</div>
    
    
<%= render 'profiles/footer' %>