config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index'

  resources :profiles
  resources :ordering_links
  devise_for :admins
  resources :socials
  get 'pages/index'
  get 'pages/order_online'
  get 'pages/about'
  
  scope :admins do
    root :to => 'dashboards#index', :as => :admin_root
  end
  
  root 'pages#index'

end

app/models/ordering_link.rb
class OrderingLink < ActiveRecord::Base
end

app/controllers/ordering_links_controller.rb
class OrderingLinksController < ApplicationController
  before_action :set_ordering_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /ordering_links
  # GET /ordering_links.json
  def index
    @ordering_links = OrderingLink.all
  end

  # GET /ordering_links/1
  # GET /ordering_links/1.json
  def show
  end

  # GET /ordering_links/new
  def new
    @ordering_link = OrderingLink.new
  end

  # GET /ordering_links/1/edit
  def edit
  end

  # POST /ordering_links
  # POST /ordering_links.json
  def create
    @ordering_link = OrderingLink.new(ordering_link_params)

    respond_to do |format|
      if @ordering_link.save
        format.html { redirect_to @ordering_link, notice: 'Ordering link was successfully created.' }
        format.json { render :show, status: :created, location: @ordering_link }
      else
        format.html { render :new }
        format.json { render json: @ordering_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordering_links/1
  # PATCH/PUT /ordering_links/1.json
  def update
    respond_to do |format|
      if @ordering_link.update(ordering_link_params)
        format.html { redirect_to @ordering_link, notice: 'Ordering link was successfully updated.' }
        format.json { render :show, status: :ok, location: @ordering_link }
      else
        format.html { render :edit }
        format.json { render json: @ordering_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordering_links/1
  # DELETE /ordering_links/1.json
  def destroy
    @ordering_link.destroy
    respond_to do |format|
      format.html { redirect_to ordering_links_url, notice: 'Ordering link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordering_link
      @ordering_link = OrderingLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ordering_link_params
      params.require(:ordering_link).permit(:url)
    end
end

app/helpers/ordering_links_helper.rb
module OrderingLinksHelper
end

app/views/ordering_links/_form.html.erb
<%= form_for(@ordering_link) do |f| %>
  <% if @ordering_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ordering_link.errors.count, "error") %> prohibited this ordering_link from being saved:</h2>

      <ul>
      <% @ordering_link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ordering_links/edit.html.erb
<h1>Editing Ordering Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @ordering_link %> |
<%= link_to 'Back', ordering_links_path %>

app/views/ordering_links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ordering Links</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ordering_links.each do |ordering_link| %>
      <tr>
        <td><%= ordering_link.url %></td>
        <td><%= link_to 'Show', ordering_link %></td>
        <td><%= link_to 'Edit', edit_ordering_link_path(ordering_link) %></td>
        <td><%= link_to 'Destroy', ordering_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ordering link', new_ordering_link_path %>

app/views/ordering_links/new.html.erb
<h1>New Ordering Link</h1>

<%= render 'form' %>

<%= link_to 'Back', ordering_links_path %>

app/views/ordering_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @ordering_link.url %>
</p>

<%= link_to 'Edit', edit_ordering_link_path(@ordering_link) %> |
<%= link_to 'Back', ordering_links_path %>