config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index'

  resources :profiles
  resources :ordering_links
  devise_for :admins
  resources :socials
  get 'pages/index'
  get 'pages/order_online'
  get 'pages/about'
  
  scope :admins do
    root :to => 'dashboards#index', :as => :admin_root
  end
  
  root 'pages#index'

end

app/models/social.rb
class Social < ActiveRecord::Base
    belongs_to :admin
end

app/controllers/socials_controller.rb
class SocialsController < ApplicationController
  before_action :set_social, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /socials
  # GET /socials.json
  def index
    @socials = Social.all
  end

  # GET /socials/1
  # GET /socials/1.json
  def show
  end

  # GET /socials/new
  def new
    @social = Social.new
  end

  # GET /socials/1/edit
  def edit
  end

  # POST /socials
  # POST /socials.json
  def create
    @social = Social.new(social_params)

    respond_to do |format|
      if @social.save
        format.html { redirect_to @social, notice: 'Social was successfully created.' }
        format.json { render :show, status: :created, location: @social }
      else
        format.html { render :new }
        format.json { render json: @social.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /socials/1
  # PATCH/PUT /socials/1.json
  def update
    respond_to do |format|
      if @social.update(social_params)
        format.html { redirect_to @social, notice: 'Social was successfully updated.' }
        format.json { render :show, status: :ok, location: @social }
      else
        format.html { render :edit }
        format.json { render json: @social.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /socials/1
  # DELETE /socials/1.json
  def destroy
    @social.destroy
    respond_to do |format|
      format.html { redirect_to socials_url, notice: 'Social was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_social
      @social = Social.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def social_params
      params.require(:social).permit(:facebook, :twitter, :instagram)
    end
end

app/helpers/socials_helper.rb
module SocialsHelper
end

app/views/socials/_form.html.erb
<%= form_for(@social) do |f| %>
  <% if @social.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@social.errors.count, "error") %> prohibited this social from being saved:</h2>

      <ul>
      <% @social.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :instagram %><br>
    <%= f.text_field :instagram %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/socials/edit.html.erb
<h1>Editing Social</h1>

<%= render 'form' %>

<%= link_to 'Show', @social %> |
<%= link_to 'Back', socials_path %>

app/views/socials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Socials</h1>

<table>
  <thead>
    <tr>
      <th>Facebook</th>
      <th>Twitter</th>
      <th>Instagram</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @socials.each do |social| %>
      <tr>
        <td><%= social.facebook %></td>
        <td><%= social.twitter %></td>
        <td><%= social.instagram %></td>
        <td><%= link_to 'Show', social %></td>
        <td><%= link_to 'Edit', edit_social_path(social) %></td>
        <td><%= link_to 'Destroy', social, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Social', new_social_path %>

app/views/socials/new.html.erb
<h1>New Social</h1>

<%= render 'form' %>

<%= link_to 'Back', socials_path %>

app/views/socials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Facebook:</strong>
  <%= @social.facebook %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @social.twitter %>
</p>

<p>
  <strong>Instagram:</strong>
  <%= @social.instagram %>
</p>

<%= link_to 'Edit', edit_social_path(@social) %> |
<%= link_to 'Back', socials_path %>